services:
    exs_bulk_email_checker.bulk_email_checker_manager:
        class: 'EXS\BulkEmailCheckerBundle\Services\BulkEmailCheckerManager'
        arguments:
            - '%exs_bulk_email_checker.config%'

    exs_bulk_email_checker.bulk_email_checker_validator:
        class: 'EXS\BulkEmailCheckerBundle\Validator\Constraints\BulkEmailCheckerValidator'
        arguments:
            - '@exs_bulk_email_checker.bulk_email_checker_manager'
        tags:
            - { name: 'validator.constraint_validator' }
